### PR TITLE
New blackpill board

### PR DESCRIPTION
**Pull request by coderkalyan**
Adds the WeAct blackpill V3.0 board with the STM32F401CE chip, 96K SRAM and 512K flash. I pulled updated schematics from WeAct's github, but copied the picture from the other blackpill definitions as they are virtually the same (besides the label on the processor).

Let me know if I forgot anything, this being my first PR to this project. Additionally, is there anything I should be adding to the main STM32-base project, or not? I haven't used that project, I usually just use the github pages site for reference, but I'm happy to make a PR for that if anything needs to be added to any other repositories.

### CODE REVIEW

**Comment by ThomasGravekamp** [comment]
Thanks for your contribution!

The only thing you seem to have missed is adding this board to the `index.json` file in the boards directory. That is simply its markdown filename minus the `.md` extension. 

I did not go over the actual contents of the data files, I assume that most of the data is the same as for the 2.0 version of this board. Do you happen to have an overview of things changed between version 2.0 and version 3.0?

I see that you have recycled the images of the 2.0 version of this board. I want to have pictures of an actual version 3.0 board for this page. And you're lucky with that one, since I already happen to have a version 3.0 board here, but didn't get to adding it to the website yet. I'll try to take pictures of that board and add them here.

You don't have to make changes to any of the other repositories. The website, and especially the boards section, is more or less a project on its own. STM32-base supports devices rather than specific boards, so there are no board definitions or whatever.

**Comment by coderkalyan** [comment]
@ThomasGravekamp Thanks, I just added the listing in index.json.

As for 2.0 vs 3.0: The board I have is the F401CE 3.0, which has some minor manufacturing changes listed on WeAct's github (https://github.com/WeActTC/MiniF4-STM32F4x1) but the only practical difference is that the F401CE has 96K SRAM, 512K flash, and 84Mhz clock - the F401CC board (no longer manufactured by weact) had only 64K SRAM and 256K flash, while the F411CE board has 128K SRAM, 512K flash, and 100Mhz clock.

As for the pictures, that's great that you have a board. Keep in mind that I believe there is a F411CE 3.0 board as well (with the same manufacturing improvements but keeping the same specs as the 2.0 F411CE board) so make sure you have the F401CE board before taking the picture.

**Comment by ThomasGravekamp** [comment]
I do happen to have the F411CE 3.0 version of this board. But I would rather have a v3.0 board than a v2.0 board with the right chip. There are more boards for which the PCB is identical, but only the microcontroller differences.

So if you have got this exact board, would you be so kind and take pictures of it to add them to this page? If not, I'll add pictures of the F411CE 3.0 board instead.

**Comment by ThomasGravekamp** [comment]
I've added the pictures of the STM32F411CEU6 variant of this board. Thanks for your contribution!

**Comment by coderkalyan** [comment]
@ThomasGravekamp Sorry, I've been busy and haven't had a chance to take a picture. If/when I have time, I'll open a new PR with the updated pictures!

**Pull request merged**
